server:
  port: 10086

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/jx191209?serverTimezone=GMT&characterEncoding=utf-8&useSSL=false
  application:
    name: user-client

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:SqlMapConfig.xml


eureka:
  client:
    fetch-registry: true #是否从eureka服务器获取各个微服务地址
    register-with-eureka: true #是否注册到eureka服务器
    service-url:
      defaultZone: http://localhost:10087/eureka/

